FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\rlCImGuiBeef.bf", "d:\\Software\\Beef\\BeefLibs\\imgui-beef-quandini-docking\\src\\ImGui.bf", "src\\ImGuiRaylibExtension.bf", "example\\src\\Program.bf", "exemple\\src\\Program.bf", "Disassembly", "Disassembly", "Disassembly", "Disassembly"]

[MainWindow]
X = 0
Y = 148
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 341.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 110.9091
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGuiRaylibExtension.bf"
TabWidth = 162.7273
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ImGuiRaylibExtension.bf"
CursorPos = 3584
VertPos = 2872.2
ProjectName = "rlCImGuiBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Program.bf"
TabWidth = 91.81818
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "example\\src\\Program.bf"
CursorPos = 356
ProjectName = "example"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImGui.bf"
TabWidth = 77.27273
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\Software\\Beef\\BeefLibs\\imgui-beef-quandini-docking\\src\\ImGui.bf"
CursorPos = 335173
VertPos = 169730.0
ProjectName = "ImGui"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "rlCImGuiBeef.bf"
TabWidth = 116.3636
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\rlCImGuiBeef.bf"
CursorPos = 2532
VertPos = 1760.0
ProjectName = "rlCImGuiBeef"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 644.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.90909
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 116.3636
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 102.7273
TabIsPinned = false
Type = "CallStackPanel"

[[Breakpoints]]
Symbol = "ImGuiRenderTriangles"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
