FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\Program.bf", "d:\\Programming\\Beef\\rlImGuiBeef\\src\\rlImGuiBeef.bf", "d:\\Programming\\Cpp\\Raylib\\rlImGui\\rlImGui.cpp", "Disassembly"]

[MainWindow]
X = 742
Y = 0
Width = 1178
Height = 884
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 834.0
SizePriority = 834.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 200.0
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 200.0
SizePriority = 0.3673998
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 111.7021
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets]]
RequestedWidth = 1918.0
RequestedHeight = 207.0
SizePriority = 0.6326002
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Autocomplete"
TabWidth = 129.7872
TabIsPinned = false
Type = "AutoCompletePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 1667.0
RequestedHeight = 150.0
SizePriority = 1667.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 92.76598
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Program.bf"
CursorPos = 481
ProjectName = "example"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "rlImGui.cpp"
TabWidth = 94.89364
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "d:\\Programming\\Cpp\\Raylib\\rlImGui\\rlImGui.cpp"
CursorPos = 14959

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 319.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 319.0
SizePriority = 1920.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.42554
TabIsPinned = false
Type = "OutputPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Errors"
TabWidth = 81.9149
TabIsPinned = false
Type = "ErrorsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Modules"
TabWidth = 98.93618
TabIsPinned = false
Type = "ModulePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 93.61703
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Profile"
TabWidth = 86.17022
TabIsPinned = false
Type = "ProfilePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Bookmarks"
TabWidth = 111.7021
TabIsPinned = false
Type = "BookmarksPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Breakpoints"
TabWidth = 115.9575
TabIsPinned = false
Type = "BreakpointPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 117.0213
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 108.5107
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 96.80852
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.17022
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Auto Watches"
TabWidth = 128.7234
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 318.0
RequestedHeight = 415.24
SizePriority = 1920.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Call Stack"
TabWidth = 103.1915
TabIsPinned = false
Type = "CallStackPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
